variables:
  BASE_DIR: "/builds/syamashi/amygdalar"
  DOCKER_DRIVER: overlay2  

stages:
  - build
  - test
  - deploy

before_script:
  - export DOCKER_HOST="tcp://localhost:2375"
  - export DISPLAY=localhost:0.0  
    
build_job:
   stage: build
   only:
    - master
   script:
    - cd ./bla-carousel3d
    - npm install
    - export NODE_ENV=production
    - npm run build
   artifacts:
     paths:
      - "./bla-carousel3d/dist/*"

test_job:
  stage: test
  only:
    - master
  script:
    - cd ./compose_skelton
    - docker-compose up --build -d
    - pwd
    - cd ../scripts
    - ls -alth
    - python test_bla_carousel3d.py
#  artifacts:
#    paths:
#     - "./bla-carousel3d/scripts/selelinum_test_results.log"

deploy_job:
  stage: deploy
  only:
    - development
  script:
    - cd ./bla-carousel3d
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e ssh syamashi@mcpweb-dev.loni.usc.edu "rm /var/www/amygdalar/static/js/*"
    - sshpass -e ssh syamashi@mcpweb-dev.loni.usc.edu "rm /var/www/amygdalar/static/css/*"    
    - sshpass -e scp -o stricthostkeychecking=no ./dist/index.html syamashi@mcpweb-dev.loni.usc.edu:/var/www/amygdalar/
    - sshpass -e scp -o stricthostkeychecking=no -r ./dist/static syamashi@mcpweb-dev.loni.usc.edu:/var/www/amygdalar/
  when: on_success

deploy_production_job:
  stage: deploy
  only:
    - tags
  except:
    - branches    
  script:
    - cd ./bla-carousel3d
    - sshpass -V
    - export SSHPASS=$USER_PASS_PROD
    - sshpass -e ssh syamashi@image6.mcp.loni.usc.edu "rm /var/www/amygdalar/static/js/*"
    - sshpass -e ssh syamashi@image6.mcp.loni.usc.edu "rm /var/www/amygdalar/static/css/*"
    - sshpass -e scp -o stricthostkeychecking=no ./dist/index.html mcpadmin@image6.mcp.loni.usc.edu:/var/www/amygdalar/
    - sshpass -e scp -o stricthostkeychecking=no -r ./dist/static mcpadmin@image6.mcp.loni.usc.edu:/var/www/amygdalar/
  when: on_success  
  
clean_job:
  stage: deploy
  only:
    - master
  script:
    - cd ./compose_skelton
    - docker-compose down -v
  when: always
  

