version: '3.2'

networks:
  local:

volumes:
  nfs_test:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs-ifs.ini.usc.edu,ro"
      device: ":/ifs/data/loni/faculty/dong/mcp"
  nfs_web_test:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs-ifs.ini.usc.edu,ro"
      device: ":/ifs/data/loni/mcpweb/mcp"
  db-data:

services:  
  httpd:
    container_name: httpd-container
    build: ./Apache
    ports:
      - "80:80"
    volumes:
      - "nfs_test:/ifs/mcp/web"
      - "nfs_web_test:/ifs/web"  

      - ../bla-carousel3d/dist/index.html:/var/www/amygdalar/index.html
      - ../bla-carousel3d/dist/static:/var/www/amygdalar/static

      # Test out vue-carousel3d
      # - ../vue-carousel3d/index.html:/var/www/amygdalar/index.html
      # - ../vue-carousel3d/js:/var/www/amygdalar/js
      # - ../vue-carousel3d/css:/var/www/amygdalar/css      

      # Test out angularjs gallery
      # - ../angular-gallery/index.html:/var/www/amygdalar/index.html
      # - ../angular-gallery/js:/var/www/amygdalar/js
      # - ../angular-gallery/css:/var/www/amygdalar/css

      # This was for vue-gallery...
      # - ../vue-gallery/example/index.html:/var/www/amygdalar/index.html
      # - ../vue-gallery/dist/js:/var/www/amygdalar/js
      # - ../vue-gallery/dist/css:/var/www/amygdalar/css
      # - ../script/data.json:/var/www/amygdalar/data/data.json
      # - ../vue-gallery/example/index2.html:/var/www/amygdalar/index2.html