#!/usr/bin/env bash

set -eu

npm install staticrypt
./node_modules/.bin/staticrypt bla-carousel3d/dist/index.html "$PRIVATE_PAGE" && mv bla-carousel3d/dist/index_encrypted.html bla-carousel3d/dist/index.html
./node_modules/.bin/staticrypt bla-carousel3d/dist/wiringdiagram.html "$PRIVATE_PAGE" && mv bla-carousel3d/dist/wiringdiagram_encrypted.html bla-carousel3d/dist/wiringdiagram.html

echo "Page successfully encrypted."
