name: GitHub Pages deployment

on:
    push:
        branches:
        - gh-deployment

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Go to project folder
        run: cd bla-carousel3d/
      
      - name: Install dependencies 
        run: npm install
      
      - name: Build
        run: npm run build 
      
      - name: Deploy
        run: ./.github/workflows/update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}