name: GitHub Pages deployment

on:
    push:
        branches:
        - gh-deployment
        - master

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Deploy
        if: github.ref == 'refs/heads/gh-deployment'
        run: ./.github/workflows/update-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          MAIN_BRANCH: gh-deployment
          TARGET_BRANCH: gh-pages-dev

      - name: Deploy Prod
        if: github.ref == 'refs/heads/master'
        run: ./.github/workflows/update-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          MAIN_BRANCH: master
          TARGET_BRANCH: gh-pages

    test:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies 
        run: npm install
        working-directory: ./bla-carousel3d

      - name: Test
        run: npm test
        working-directory: ./bla-carousel3d